INSERT INTO authors (id, name, bio)
VALUES (1, 'Robert C. Martin', 'Bio for Robert C. Martin'),
       (2, 'Andrew Hunt & David Thomas', 'Bio for Andrew Hunt & David Thomas'),
       (3, 'Steve McConnell', 'Bio for Steve McConnell'),
       (4, 'Erich Gamma et al.', 'Bio for Erich Gamma et al.'),
       (5, 'Martin Fowler', 'Bio for Martin Fowler'),
       (6, 'Eric Evans', 'Bio for Eric Evans'),
       (7, 'Joshua Bloch', 'Bio for Joshua Bloch'),
       (8, 'Jez Humble & David Farley', 'Bio for Jez Humble & David Farley'),
       (9, 'Frederick P. Brooks Jr.', 'Bio for Frederick P. Brooks Jr.'),
       (10, 'Betsy Beyer et al.', 'Bio for Betsy Beyer et al.'),
       (11, 'Martin Fowler', 'Bio for Martin Fowler'),
       (12, 'Michael Nygard', 'Bio for Michael Nygard'),
       (13, 'Michael Feathers', 'Bio for Michael Feathers'),
       (14, 'Eric Freeman & Elisabeth Robson', 'Bio for Eric Freeman & Elisabeth Robson'),
       (15, 'Kathy Sierra & Bert Bates', 'Bio for Kathy Sierra & Bert Bates'),
       (16, 'Dan Pilone & Russ Miles', 'Bio for Dan Pilone & Russ Miles'),
       (17, 'Gene Kim, Kevin Behr & George Spafford',
        'Bio for Gene Kim, Kevin Behr & George Spafford'),
       (18, 'Nicole Forsgren, Jez Humble & Gene Kim',
        'Bio for Nicole Forsgren, Jez Humble & Gene Kim'),
       (19, 'Kief Morris', 'Bio for Kief Morris'),
       (20, 'Yevgeniy Brikman', 'Bio for Yevgeniy Brikman'),
       (21, 'Marko Lukša', 'Bio for Marko Lukša'),
       (22, 'Nigel Poulton', 'Bio for Nigel Poulton'),
       (23, 'Kyle Simpson', 'Bio for Kyle Simpson'),
       (24, 'Marijn Haverbeke', 'Bio for Marijn Haverbeke'),
       (25, 'Douglas Crockford', 'Bio for Douglas Crockford'),
       (26, 'Kyle Simpson', 'Bio for Kyle Simpson'),
       (27, 'Mark Lutz', 'Bio for Mark Lutz'),
       (28, 'Luciano Ramalho', 'Bio for Luciano Ramalho'),
       (29, 'David Beazley & Brian K. Jones', 'Bio for David Beazley & Brian K. Jones'),
       (30, 'Herbert Schildt', 'Bio for Herbert Schildt'),
       (31, 'Brian W. Kernighan & Dennis M. Ritchie',
        'Bio for Brian W. Kernighan & Dennis M. Ritchie'),
       (32, 'Scott Meyers', 'Bio for Scott Meyers'),
       (33, 'Stanley B. Lippman et al.', 'Bio for Stanley B. Lippman et al.'),
       (34, 'W. Richard Stevens & Stephen A. Rago', 'Bio for W. Richard Stevens & Stephen A. Rago'),
       (35, 'W. Richard Stevens', 'Bio for W. Richard Stevens'),
       (36, 'Donald E. Knuth', 'Bio for Donald E. Knuth'),
       (37, 'Thomas H. Cormen et al.', 'Bio for Thomas H. Cormen et al.'),
       (38, 'Brian Christian & Tom Griffiths', 'Bio for Brian Christian & Tom Griffiths'),
       (39, 'Aditya Bhargava', 'Bio for Aditya Bhargava'),
       (40, 'Randal E. Bryant & David R. O’Hallaron',
        'Bio for Randal E. Bryant & David R. O’Hallaron'),
       (41, 'Remzi H. Arpaci-Dusseau & Andrea C. Arpaci-Dusseau',
        'Bio for Remzi H. Arpaci-Dusseau & Andrea C. Arpaci-Dusseau'),
       (42, 'Alfred V. Aho et al.', 'Bio for Alfred V. Aho et al.'),
       (43, 'Abraham Silberschatz et al.', 'Bio for Abraham Silberschatz et al.'),
       (44, 'Martin Kleppmann', 'Bio for Martin Kleppmann'),
       (45, 'Neha Narkhede, Gwen Shapira & Todd Palino',
        'Bio for Neha Narkhede, Gwen Shapira & Todd Palino'),
       (46, 'Tyler Akidau et al.', 'Bio for Tyler Akidau et al.'),
       (47, 'Kevin P. Murphy', 'Bio for Kevin P. Murphy'),
       (48, 'Christopher M. Bishop', 'Bio for Christopher M. Bishop'),
       (49, 'Aurélien Géron', 'Bio for Aurélien Géron'),
       (50, 'Ian Goodfellow, Yoshua Bengio & Aaron Courville',
        'Bio for Ian Goodfellow, Yoshua Bengio & Aaron Courville'),
       (51, 'Stuart Russell & Peter Norvig', 'Bio for Stuart Russell & Peter Norvig'),
       (52, 'Trevor Hastie, Robert Tibshirani & Jerome Friedman',
        'Bio for Trevor Hastie, Robert Tibshirani & Jerome Friedman'),
       (53, 'Andrew Trask', 'Bio for Andrew Trask'),
       (54, 'Joel Grus', 'Bio for Joel Grus'),
       (55, 'Allen B. Downey', 'Bio for Allen B. Downey'),
       (56, 'Allen B. Downey', 'Bio for Allen B. Downey'),
       (57, 'Kent Beck', 'Bio for Kent Beck'),
       (58, 'Steve Freeman & Nat Pryce', 'Bio for Steve Freeman & Nat Pryce'),
       (59, 'Robert C. Martin', 'Bio for Robert C. Martin'),
       (60, 'Robert C. Martin', 'Bio for Robert C. Martin'),
       (61, 'Paul M. Duvall', 'Bio for Paul M. Duvall'),
       (62, 'Tom DeMarco & Timothy Lister', 'Bio for Tom DeMarco & Timothy Lister'),
       (63, 'Frederick P. Brooks Jr.', 'Bio for Frederick P. Brooks Jr.'),
       (64, 'Titus Winters et al.', 'Bio for Titus Winters et al.'),
       (65, 'Sam Newman', 'Bio for Sam Newman'),
       (66, 'Chris Richardson', 'Bio for Chris Richardson'),
       (67, 'Josh Long & Kenny Bastani', 'Bio for Josh Long & Kenny Bastani'),
       (68, 'Craig Walls', 'Bio for Craig Walls'),
       (69, 'Felipe Gutierrez', 'Bio for Felipe Gutierrez'),
       (70, 'Tomasz Nurkiewicz & Benjamin Muschko', 'Bio for Tomasz Nurkiewicz & Benjamin Muschko'),
       (71, 'Brian Goetz et al.', 'Bio for Brian Goetz et al.'),
       (72, 'Stephen Cleary', 'Bio for Stephen Cleary'),
       (73, 'Dustin Metzgar', 'Bio for Dustin Metzgar'),
       (74, 'Adam Freeman', 'Bio for Adam Freeman'),
       (75, 'Michael S. Collier & Robin E. Shahan', 'Bio for Michael S. Collier & Robin E. Shahan'),
       (76, 'Ben Piper & David Clinton', 'Bio for Ben Piper & David Clinton'),
       (77, 'JJ Geewax', 'Bio for JJ Geewax'),
       (78, 'Jennifer Davis & Katherine Daniels', 'Bio for Jennifer Davis & Katherine Daniels'),
       (79, 'Gene Kim et al.', 'Bio for Gene Kim et al.'),
       (80, 'Kief Morris', 'Bio for Kief Morris'),
       (81, 'Gene Kim', 'Bio for Gene Kim'),
       (82, 'Casey Rosenthal & Nora Jones', 'Bio for Casey Rosenthal & Nora Jones'),
       (83, 'Charity Majors, Liz Fong-Jones & George Miranda',
        'Bio for Charity Majors, Liz Fong-Jones & George Miranda'),
       (84, 'Betsy Beyer et al.', 'Bio for Betsy Beyer et al.'),
       (85, 'Bilgin Ibryam & Roland Huß', 'Bio for Bilgin Ibryam & Roland Huß'),
       (86, 'Bilgin Ibryam & Roland Huß', 'Bio for Bilgin Ibryam & Roland Huß'),
       (87, 'Scott Surovich', 'Bio for Scott Surovich'),
       (88, 'Christian E. Posta', 'Bio for Christian E. Posta'),
       (89, 'Christian E. Posta', 'Bio for Christian E. Posta'),
       (90, 'Matt Klein', 'Bio for Matt Klein'),
       (91, 'Ekin Kaya', 'Bio for Ekin Kaya'),
       (92, 'Stephen H. Kan', 'Bio for Stephen H. Kan'),
       (93, 'Norman E. Fenton & Shari Lawrence Pfleeger',
        'Bio for Norman E. Fenton & Shari Lawrence Pfleeger'),
       (94, 'Anton Chuvakin & Kevin Schmidt', 'Bio for Anton Chuvakin & Kevin Schmidt'),
       (95, 'Niall Richard Murphy et al.', 'Bio for Niall Richard Murphy et al.'),
       (96, 'Cain Hu', 'Bio for Cain Hu'),
       (97, 'Stephen Berczuk & Brad Appleton', 'Bio for Stephen Berczuk & Brad Appleton'),
       (98, 'Jon Loeliger & Matthew McCullough', 'Bio for Jon Loeliger & Matthew McCullough'),
       (99, 'Scott Chacon & Ben Straub', 'Bio for Scott Chacon & Ben Straub'),
       (100, 'Adam Freeman', 'Bio for Adam Freeman');
